# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/lquinones/Documents/LeoLab/UE/UEEditor/Linux_Unreal_Engine_5.6.1

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	MyProject-Android-DebugGame  \
	MyProject-Android-Development  \
	MyProject-Android-Shipping  \
	MyProject-Linux-DebugGame  \
	MyProject-Linux-Development  \
	MyProject-Linux-Shipping  \
	MyProject-LinuxArm64-DebugGame  \
	MyProject-LinuxArm64-Development  \
	MyProject-LinuxArm64-Shipping  \
	MyProject \
	MyProjectEditor-Linux-DebugGame  \
	MyProjectEditor-Linux-Development  \
	MyProjectEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend MyProjectEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug MyProjectEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

MyProject-Android-DebugGame:
	 $(BUILD) MyProject Android DebugGame  -Project="/home/lquinones/Documents/LeoLab/UEProjects/uedev/MyProject.uproject" $(ARGS)

MyProject-Android-Development:
	 $(BUILD) MyProject Android Development  -Project="/home/lquinones/Documents/LeoLab/UEProjects/uedev/MyProject.uproject" $(ARGS)

MyProject-Android-Shipping:
	 $(BUILD) MyProject Android Shipping  -Project="/home/lquinones/Documents/LeoLab/UEProjects/uedev/MyProject.uproject" $(ARGS)

MyProject-Linux-DebugGame:
	 $(BUILD) MyProject Linux DebugGame  -Project="/home/lquinones/Documents/LeoLab/UEProjects/uedev/MyProject.uproject" $(ARGS)

MyProject-Linux-Development:
	 $(BUILD) MyProject Linux Development  -Project="/home/lquinones/Documents/LeoLab/UEProjects/uedev/MyProject.uproject" $(ARGS)

MyProject-Linux-Shipping:
	 $(BUILD) MyProject Linux Shipping  -Project="/home/lquinones/Documents/LeoLab/UEProjects/uedev/MyProject.uproject" $(ARGS)

MyProject-LinuxArm64-DebugGame:
	 $(BUILD) MyProject LinuxArm64 DebugGame  -Project="/home/lquinones/Documents/LeoLab/UEProjects/uedev/MyProject.uproject" $(ARGS)

MyProject-LinuxArm64-Development:
	 $(BUILD) MyProject LinuxArm64 Development  -Project="/home/lquinones/Documents/LeoLab/UEProjects/uedev/MyProject.uproject" $(ARGS)

MyProject-LinuxArm64-Shipping:
	 $(BUILD) MyProject LinuxArm64 Shipping  -Project="/home/lquinones/Documents/LeoLab/UEProjects/uedev/MyProject.uproject" $(ARGS)

MyProject: MyProject-Linux-Development

MyProjectEditor-Linux-DebugGame:
	 $(BUILD) MyProjectEditor Linux DebugGame  -Project="/home/lquinones/Documents/LeoLab/UEProjects/uedev/MyProject.uproject" $(ARGS)

MyProjectEditor-Linux-Development:
	 $(BUILD) MyProjectEditor Linux Development  -Project="/home/lquinones/Documents/LeoLab/UEProjects/uedev/MyProject.uproject" $(ARGS)

MyProjectEditor: MyProjectEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/lquinones/Documents/LeoLab/UEProjects/uedev/MyProject.uproject" -Game 

.PHONY: $(TARGETS)
